exception_with_retry
