msgid ""
msgstr ""
"Project-Id-Version: pylav\n"
"POT-Creation-Date: 2022-12-30 22:38+0000\n"
"PO-Revision-Date: 2023-01-11 14:16\n"
"Last-Translator: \n"
"Language-Team: Chinese Traditional\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.4.2\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: pylav\n"
"X-Crowdin-Project-ID: 535244\n"
"X-Crowdin-Language: zh-TW\n"
"X-Crowdin-File: /pylav/extension/bundled_node/locales/messages.pot\n"
"X-Crowdin-File-ID: 721\n"
"Language: zh_TW\n"

#: pylav/extension/bundled_node/manager.py:227
msgid "You are attempting to run the managed Lavalink node on an unsupported machine architecture"
msgstr "您正在嘗試在不受支持的機器架構上運行託管的 Lavalink 節點"

#: pylav/extension/bundled_node/manager.py:452
msgid "The output of `{java_exc} -version` was unexpected\n"
"{version_info}"
msgstr "由 `{java_exc} -version` 的輸出是有問題的\n"
"{version_info}"

#: pylav/extension/bundled_node/manager.py:472
msgid "Port {port} already in use. Managed Lavalink startup aborted"
msgstr "端口 {port} 已在使用中。託管的 Lavalink 將啟動中止"

#: pylav/extension/bundled_node/manager.py:477
msgid "Lavalink failed to start: {line}"
msgstr "Lavalink 啟動失敗：{line}"

